### PR TITLE
Update Runtime to 23.08

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by bbhtt** [comment]
Can you remove libwebp? This should be in the runtime and includes a recent security fix https://github.com/flathub/tv.plex.PlexDesktop/pull/41

**Comment by JakobDev** [comment]
> Can you remove libwebp?

Done

**Comment by averms** [comment]
> Build [65409 successful](https://buildbot.flathub.org/#/builders/6/builds/65409) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/48047/tv.plex.PlexDesktop.flatpakref
> ```

Testing this gives `/app/bin/../bin/plex-bin: error while loading shared libraries: libwebp.so.6: cannot open shared object file: No such file or directory`. The runtime has a too-new version of libwebp.

**Comment by bbhtt** [comment]
That sucks, it's stuck on an outdated version of a library...

**Comment by prodrigestivill** [comment]
Strangely this app is using both ABI versions (6 & 7):

```
flatpak run --branch=stable --command=ldd tv.plex.PlexDesktop /app/bin/plex-bin | grep libwebp
	libwebpmux.so.3 => /usr/lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007fd24a34a000)
	libwebpdemux.so.2 => /app/bin/./../lib/libwebpdemux.so.2 (0x00007fd247a4f000)
	libwebp.so.6 => /app/bin/./../lib/libwebp.so.6 (0x00007fd23d663000)
	libwebp.so.7 => /usr/lib/x86_64-linux-gnu/libwebp.so.7 (0x00007fd23cb18000)
```

As seen current build (with 21.08 runtime) ships the old version even that the runtime already have the new ABI.
So I assume c61414a is not required, as it seams the application requires both versions.

**Comment by TobiTenno** [comment]
any chance we can get these updates published? it'd be nice to be on the newer runtime versions, as 21.08 is now deprecated

**Review by TobiTenno — APPROVED** [review]
made the same changes and built locally and it works for me, too

**Comment by bbhtt** [comment]
> 	libwebp.so.6 => /app/bin/./../lib/libwebp.so.6 (0x00007fd23d663000)
	libwebp.so.7 => /usr/lib/x86_64-linux-gnu/libwebp.so.7 (0x00007fd23cb18000)

That's very weird, it should not link against both...

@JakobDev Can you revert the libwebp changes? Thanks.

> any chance we can get these updates published?

I've assigned it to the maintainers, if no one responds I'll merge in a while.

**Review by rubenamorim — APPROVED** [review]
I'm not able to test, but the changes look good.

**Comment by bbhtt** [comment]
bot, build

I can test and do changes if needed.

**Comment by bbhtt** [comment]
Crashes immediately:

```
flatpak run tv.plex.PlexDesktop                                                              
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
qt.scenegraph.general: Using QRhi with backend OpenGL
  Graphics API debug/validation layers: 0
  QRhi profiling and debug markeqt.scenegraph.general: Using QRhi with backend OpenGL
  Graphics API debug/validation layers: 0
  QRhi profiling and debug markers: 0
  Shader/pipeline cache collection: 0
rs: 0
  Shader/pipeline cache collection: 0
/app/bin/Plex: line 48:     5 Aborted                 (core dumped) "$BASE_DIR"/bin/plex-bin "$@"
```

**Comment by miostreams** [comment]
> Build [77073 successful](https://buildbot.flathub.org/#/builders/6/builds/77073) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/59661/tv.plex.PlexDesktop.flatpakref
> ```

Crashes immediately:

libGL error: MESA-LOADER: failed to open iris: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/iris_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/iris_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
qt.scenegraph.general: Using QRhi with backend OpenGL
  Graphics API debug/validation layers: 0
  QRhi profiling and debug markers: 0
  Shader/pipeline cache collection: 0
qt.scenegraph.general: Using QRhi with backend OpenGL
  Graphics API debug/validation layers: 0
  QRhi profiling and debug markers: 0
  Shader/pipeline cache collection: 0
/app/bin/Plex: line 48:     5 Aborted                 (core dumped) "$BASE_DIR"/bin/plex-bin "$@"

**Comment by pnitram** [comment]
Tested another build where only change is runtime changed to 23.08. 

#49 

# Crashes when using Intel GPU

flatpak run tv.plex.PlexDesktop
libGL error: MESA-LOADER: failed to open iris: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/iris_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so: undefined symbol: amdgpu_cs_ctx_stable_pstate (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
qt.scenegraph.general: Using QRhi with backend OpenGL
Graphics API debug/validation layers: 0
QRhi profiling and debug markers: 0
Shader/pipeline cache collection: 0
qt.scenegraph.general: Using QRhi with backend OpenGL
Graphics API debug/validation layers: 0
QRhi profiling and debug markers: 0
Shader/pipeline cache collection: 0
/app/bin/Plex: line 48: 5 Aborted (core dumped) "$BASE_DIR"/bin/plex-bin "$@"
(failed reverse-i-search)`optirin': flatpak run tv.plex.PlexDeskt^C


# Running fine when starting with discrete GPU

__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia flatpak run tv.plex.PlexDesktop
qt.scenegraph.general: Using QRhi with backend OpenGL
Graphics API debug/validation layers: 0
QRhi profiling and debug markers: 0
Shader/pipeline cache collection: 0
qt.scenegraph.general: Using QRhi with backend OpenGL
Graphics API debug/validation layers: 0
QRhi profiling and debug markers: 0
Shader/pipeline cache collection: 0
Dolby, Dolby Digital, Dolby Digital Plus, Dolby TrueHD and the double D symbol are trademarks of Dolby Laboratories.

**Comment by prodrigestivill** [comment]
I continued this work on #50.

And I managed to make it work in the local builds using Intel MESA drivers and NVIDIA proprietary drivers.

Can't test using AMD, hopefully some body can test the flathub build there.

**Comment by bbhtt** [comment]
Closing in favour of https://github.com/flathub/tv.plex.PlexDesktop/pull/50

**Pull request closed without merging**
